import Head from 'next/head'
import Form from '../components/Form'
import styles from './Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>EFFICIENT LIST</h1>
        <Form />
      </main>
    </>
  )
}
