import Head from 'next/head'
import SignUp from '../components/SignUp'
import styles from './Home.module.css'

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Efficient List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SignUp />
      </main>
    </>
  )
}

export default Home
